### ISSUE TITLE
Blank Screen?

### ISSUE THREAD

**Issue by z3t0** [remirobert/CameraEngine#22]
Hi I am trying to follow the Quick Start on the README.md and have a blank screen when I run the app.

```swift
import UIKit
import CameraEngine


class ViewController: UIViewController {
    
    let cameraEngine =  CameraEngine()

    override func viewDidLoad() {
        super.viewDidLoad()
        self.cameraEngine.startSession()
        
}

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    override func viewDidLayoutSubviews() {
        let layer = self.cameraEngine.previewLayer
        
        layer.frame = self.view.bounds
        self.view.layer.insertSublayer(layer, atIndex: 0)
        self.view.layer.masksToBounds = true
        
    
    }
    
  


}

```

Please refer to the code here, any help appreciated

**Comment by z3t0** [comment]
I am getting this in Xcode after running the app:
```
dyld: Library not loaded: @rpath/CameraEngine.framework/CameraEngine
  Referenced from: /var/containers/Bundle/Application/6860F7C3-7CB3-45C8-A181-0652753E0FE4/	.app/	
  Reason: image not found
(lldb) 
```

I'm not too sure what this means...

**Comment by z3t0** [comment]
OK so now I have fixed the error above, but now all I get is a black screen... no errors this time

**Comment by remirobert** [comment]
Yes, that's because you use it on a simulator. You need a real device, to interact with the camera hardware. No virtual solution is currently implemented on the simulator.

**Comment by z3t0** [comment]
Actually I am using a real device. It seems there's a problem with my story board.

**Comment by remirobert** [comment]
put a ```print("yo") ``` in the ```viewDidLoad``` method. Maybe you forgot to bind the *UIViewController* in your *Storyboard* with your file.
